# Generated by Django 3.0.7 on 2020-10-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Subscribe',
        ),
    ]
