# Generated by Django 3.0.7 on 2020-10-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
    ]
