# Generated by Django 2.1.7 on 2021-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201030_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('zip', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=40)),
                ('degree', models.CharField(max_length=40)),
                ('university', models.CharField(max_length=40)),
                ('certificate', models.CharField(max_length=40)),
                ('experience', models.CharField(max_length=40)),
                ('week', models.CharField(max_length=40)),
                ('medium', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
        ),
    ]
