# Generated by Django 2.1.7 on 2021-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_teacher_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_sign',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher_sign',
            name='zip',
        ),
        migrations.AlterField(
            model_name='teacher_sign',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher_sign',
            name='experience',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='teacher_sign',
            name='week',
            field=models.CharField(max_length=4),
        ),
    ]
