# Generated by Django 2.1.7 on 2021-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210426_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_sign',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='teacher_sign',
            name='photo',
        ),
        migrations.AddField(
            model_name='teacher_sign',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher_sign',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
