# Generated by Django 2.1.7 on 2021-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210426_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('zip', models.IntegerField(null=True)),
                ('degree', models.CharField(max_length=40)),
                ('school', models.CharField(max_length=40)),
                ('experience', models.CharField(max_length=4)),
                ('week', models.CharField(max_length=4)),
                ('medium', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
        ),
    ]
