# Generated by Django 2.1.7 on 2021-05-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_student_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_sign',
            name='subject',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='teacher_sign',
            name='subject',
            field=models.CharField(default='', max_length=40),
        ),
    ]
